apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28 # this image, run a task then exit, otherwise, it will status CrashLoopBackOff
      command: ['sh', '-c', 'echo the app is running && sleep 3600']
      env:
        - name: FIRSTNAME
          value: "raksmey"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c']
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done']
    - name: init-mydb
      image: busybox:1.28
      command: [ 'sh', '-c' ]
      args: [ 'until nslookup mydb.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done' ]
