apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ns1
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx

