apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never # Always, Never, OnFailure
  containers:
    - name: ubuntu
      image: ubuntu
      args:
        - "/bin/sh"
        - "-c"
        - "echo this is my path: $PATH"
